# Generated by Django 5.1 on 2024-08-25 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('annee_inscription', models.CharField(max_length=4)),
                ('statut', models.CharField(choices=[('En cours de formation', 'En cours de formation'), ('Diplômé', 'Diplômé'), ('Exclus', 'Exclus')], default='En cours de formation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='connexion.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.FloatField()),
                ('semestre', models.CharField(choices=[('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2')], max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='connexion.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField()),
                ('type_note', models.CharField(choices=[('note1', 'Note 1'), ('note2', 'Note 2'), ('note1_et_note2', 'Note 1 et Note 2')], max_length=20)),
                ('semestre', models.CharField(choices=[('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.CharField(default='1999-2000', max_length=9)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='connexion.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='connexion.matiere')),
            ],
        ),
    ]
