# Generated by Django 5.1 on 2024-09-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_note_classe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matiere',
            constraint=models.UniqueConstraint(fields=('name', 'classe'), name='unique_matiere_per_classe'),
        ),
    ]
