# Generated by Django 5.1 on 2024-09-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_matiere_unique_matiere_per_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
