# Generated by Django 5.1 on 2024-09-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0004_matiere_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_scolaire_en_cours',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
