# Generated by Django 5.1 on 2024-09-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_etudiant_annee_scolaire_en_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('filiere', models.CharField(choices=[('AS', 'Analyste Statisticien'), ('ISEP', 'Ingénieur Statisticien Economiste Préparatoire'), ('ISE', 'Ingénieur Statisticien Economiste')], max_length=4)),
            ],
        ),
    ]
