# Generated by Django 5.1 on 2024-09-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
