# Generated by Django 5.1 on 2024-09-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0007_alter_responsable_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
