# Generated by Django 5.1 on 2024-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0009_responsable_created_at_responsable_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='responsable',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
