# Generated by Django 5.1 on 2024-09-12 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0010_etudiant_last_login_responsable_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='connexion.etudiant')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='connexion.responsable')),
            ],
        ),
    ]
