# Generated by Django 5.1 on 2024-09-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='Messages_fichiers/'),
        ),
    ]
