# Generated by Django 5.1 on 2024-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0012_message_fichier_joint'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sujet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
