# Generated by Django 5.1 on 2024-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0013_message_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
