# Generated by Django 5.1 on 2024-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0014_message_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visible_etudiant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='visible_responsable',
            field=models.BooleanField(default=True),
        ),
    ]
