# Generated by Django 5.1 on 2024-09-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0015_message_visible_etudiant_message_visible_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='fichier_joint',
        ),
        migrations.CreateModel(
            name='FichiersJoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='Messages_fichiers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichier_joint', to='connexion.message')),
            ],
        ),
    ]
