# Generated by Django 5.1 on 2024-09-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0016_remove_message_fichier_joint_fichiersjoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motif_exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplome', to='connexion.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Exclu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclu', to='connexion.etudiant')),
                ('motif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motif_exclusion', to='connexion.motif_exclusion')),
            ],
        ),
    ]
