# Generated by Django 5.1 on 2024-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0017_motif_exclusion_diplome_exclu'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_diplomation',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='annee_exclusion',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
