# Generated by Django 5.1 on 2024-11-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0018_etudiant_annee_diplomation_etudiant_annee_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='poids',
            field=models.FloatField(default=0.5, max_length=3),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='filiere',
            field=models.CharField(choices=[('AS', 'Analyste Statisticien'), ('ISEP', 'Ingénieur Statisticien Economiste Préparatoire'), ('ISE1', 'Ingénieur Statisticien Economiste première année'), ('ISE', 'Ingénieur Statisticien Economiste ')], max_length=4),
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='connexion.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='connexion.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='connexion.matiere')),
            ],
        ),
    ]
