# Generated by Django 5.1 on 2024-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0019_note_poids_alter_responsable_filiere_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyenne',
            name='annee_scolaire',
            field=models.CharField(default='1999-2000', max_length=9),
        ),
    ]
