# Generated by Django 5.1 on 2024-11-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0020_moyenne_annee_scolaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
