# Generated by Django 5.1 on 2024-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0021_etudiant_date_naissance_etudiant_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='nombre_redoublage',
            field=models.IntegerField(default=0),
        ),
    ]
