# Generated by Django 5.1 on 2024-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0022_etudiant_nombre_redoublage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
