# Generated by Django 5.1 on 2024-11-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0023_alter_matiere_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='heure_absence',
            field=models.IntegerField(default=0),
        ),
    ]
