# Generated by Django 5.1 on 2025-04-02 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0025_enseignants_matiere_enseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDeTemps',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(choices=[('semestre1', 'Semestre 1'), ('semestre2', 'Semestre 2')], max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emploi_de_temps', to='connexion.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Programmation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horaire', models.CharField(max_length=100)),
                ('emploi_de_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmation', to='connexion.emploidetemps')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmation', to='connexion.matiere')),
            ],
        ),
    ]
