# Generated by Django 5.1 on 2025-04-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0026_emploidetemps_programmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enseignants',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
