# Generated by Django 5.1 on 2025-04-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0027_enseignants_is_permanent_enseignants_nationalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignants',
            name='sexe',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
