# Generated by Django 5.1 on 2025-04-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0030_emploidutemps_created_at_emploidutemps_updated_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emploidutemps',
            constraint=models.UniqueConstraint(fields=('periode', 'classe'), name='unique_emploi_du_temps'),
        ),
    ]
